excludes:
  paths:
  - pattern: "examples/**"
    reason: "EXAMPLE_OF"
    comment: "Examples we don't use"
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation"
  - pattern: "testsuite/**"
    reason: "TEST_TOOL_OF"
    comment: "Tests"
  - pattern: "quarkus/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Quarkus is another distribution"
  - pattern: "distribution/example-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for another distribution"
  - pattern: "distribution/adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "distribution/licenses-common/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are irrelevant and will not be distributed"
  - pattern: "distribution/server-x-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "distribution/saml-adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "misc/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  scopes:
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
    
resolutions:
  vulnerabilities:
  - id: "sonatype-2019-0282"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-1694"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-1694"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-0926"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-42575"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-42575"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2018-14335"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-1324"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-0341"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2018-20200"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-0341"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2012-0050"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2015-0002"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2015-6420"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37136"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37137"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-0026"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0789"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37136"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37137"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0789"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37136"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37137"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-21290"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-21290"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-0026"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2016-6311"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3597"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3690"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2019-17571"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2010-0053"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2019-17571"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2019-12402"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35515"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35516"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35517"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-36090"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2019-12402"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35515"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35516"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-35517"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-36090"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2007-0020"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0591"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-12629"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-12629"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-26291"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-26291"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-40690"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-40690"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-30129"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-30129"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2019-0673"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2020-17521"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2015-0173"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-1438"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2020-1732"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2016-4978"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2016-4978"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-20318"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2020-14297"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2010-0053"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2020-25633"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2016-6348"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-20289"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2018-1051"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2020-14340"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37714"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37714"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2012-0126"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2016-6311"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3642"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37136"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-37137"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-0026"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2020-0926"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0789"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0864"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-7503"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3644"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3642"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2021-3642"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2021-0864"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-18640"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-18640"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-18640"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "CVE-2017-18640"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2017-0348"
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
  - id: "sonatype-2016-0398"    
    reason: "INEFFECTIVE_VULNERABILITY"
    comment: "Baseline waiving. Takinng result from BCI scan"
