excludes:
  paths:
  - pattern: "examples/**"
    reason: "EXAMPLE_OF"
    comment: "Examples we don't use"
  - pattern: "docs/**"
    reason: "DOCUMENTATION_OF"
    comment: "Documentation"
  - pattern: "testsuite/**"
    reason: "TEST_TOOL_OF"
    comment: "Tests"
  - pattern: "quarkus/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Quarkus is another distribution"
  - pattern: "distribution/example-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for another distribution"
  - pattern: "distribution/adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "distribution/licenses-common/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are irrelevant and will not be distributed"
  - pattern: "distribution/server-x-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "distribution/saml-adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "distribution/downloads/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/maven-plugins/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/api-docs-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/feature-packs/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/galleon-feature-packs/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/server-legacy-dist/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "distribution/server-overlay/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "These files are not part of the docker image that is used"
  - pattern: "adapters/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  - pattern: "misc/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Those are files for integration"
  scopes:
  - pattern: "test"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."
  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."
